version: "3.1"
services:
  project-db:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  project-drupal:
    image: drupal:7.59-apache
    volumes:
      - ./sites/:/var/www/html/sites
    ports:
      - "8080:80"
    restart: always  
    links:
      - project-db:mysql
  project-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
